### ISSUE TITLE
resource limit exceeded: instance count too high at 10001

### ISSUE THREAD

**Issue by bxq2011hust** [bytecodealliance/wasmtime#2751] opened 2021-03-22 15:07 UTC
I use one module to wasm_instance_new(C-API) instance to execute the function to save the cost of wasm_module_new, at start it works well, After some time running, I can't use wasm_instance_new to create new instance and got the error message `resource limit exceeded: instance count too high at 10001`. 
I freed the instance use wasm_instance_delete every time execution is done, also free the exports, I think the count of instance should decrease to zero after execution, It seems the count of instance is cumulative. Is there some way to use one module to create instances more than 10000 times?

**Comment by bjorn3** [comment] 2021-03-22 15:34
You can use `wasmtime_config_max_instances_set` which gets a `wasm_config_t*` and `size_t` as argument.

https://github.com/bytecodealliance/wasmtime/blob/6e6713ae0b0be578221a2802719327526458a8cf/crates/c-api/include/wasmtime.h#L292

**Comment by alexcrichton** [comment] 2021-03-22 17:50
It's important to note that `wasm_instance_delete` does not actually delete the underlying instance's resources, just the C object representing the instance. I don't think we have a ton of documentation for this but an instance's resources are only deallocated when the entire `Store` (or `wasm_store_t`) goes away. This means that for a long-lived use case you likely want a singular `wasm_engine_t` and the `wasm_store_t` should be ephemeral and not as long-lived.

Otherwise though, if you'd like to do this, 10000 is just the default and as mentioned you can up the limit yourself.

**Comment by bxq2011hust** [comment] 2021-03-23 01:37
@bjorn3  thank you very much, I read the `WASMTIME_CONFIG_PROP(void, max_instances, size_t) `, this can allow me to create more instance use one module. 
Also, I found `wasmtime_store_gc` in wasmtime.h, I wonder if I can use `wasmtime_store_gc` to decrease the store's count of the instance before it reaches the max_instances  so that I can use one module to create instances always?

**Comment by bxq2011hust** [comment] 2021-03-23 01:57
@alexcrichton ok, I see. Is `wasmtime_store_gc` can release the instance's resource?🤔️

If the `wasmtime_store_gc` can't release the instance's resource then I will consider recreating the `wasm_engine_t` and the `wasm_store_t` before it reaches 10000.

**Comment by peterhuene** [comment] 2021-03-23 02:13
@bxq2011hust `wasmtime_store_gc` is used to perform a garbage collection of `externref` values that may no longer be reachable; it has no relationship to instances and only has relevance if you're passing `externref` values into WebAssembly code.

In Wasmtime, a module has no relation to a store, so you can also use `wasmtime_module_new` which better encapsulates this (the store passed to `wasm_module_new` is only used to get the related engine).  

As module and engine have no relation to store, you may continue to use them after any calls to `wasm_store_delete`; thus you may create a new store each time you wish to instantiate your module.

**Comment by bxq2011hust** [comment] 2021-03-23 04:36
@peterhuene  yes, that's what I want. I tried your idea and it worked, thanks!!!😄😄

**Comment by peterhuene** [comment] 2021-03-23 04:51
@bxq2011hust may I close this issue if your problem has been resolved?

**Comment by bxq2011hust** [comment] 2021-03-23 04:56
@peterhuene  Last question. In the https://github.com/WebAssembly/wasm-c-api, it said
>>> All runtime objects are tied to a specific store (wasm::Store/wasm_store_t). Multiple stores can be created, but their objects cannot interact. Every store and its objects must only be accessed in a single thread.
It seems in one thread I need a new instance, and I surely do that now. I want to save the time cost of creating imports of function and the time of creating new instances by use one instance in multi-thread. I want to know if I call `wasm_func_call` with the same instance in multi-threads is it ok of the wasmtime engine?

**Comment by alexcrichton** [comment] 2021-03-23 15:33
It is not safe to `wasm_func_call` the same function on multiple threads, all objects connected to `wasm_store_t` (which includes `wasm_func_t`) must be used on only one thread at a time.

The Rust `wasmtime` crate has the ability to define functions in the `Engine`-scope to share them across stores  -- https://docs.rs/wasmtime/0.25.0/wasmtime/struct.Config.html#method.define_host_func -- but this is not currently exposed in the C API.

**Comment by bxq2011hust** [comment] 2021-03-24 02:15
> It is not safe to `wasm_func_call` the same function on multiple threads, all objects connected to `wasm_store_t` (which includes `wasm_func_t`) must be used on only one thread at a time.
> 
> The Rust `wasmtime` crate has the ability to define functions in the `Engine`-scope to share them across stores -- https://docs.rs/wasmtime/0.25.0/wasmtime/struct.Config.html#method.define_host_func -- but this is not currently exposed in the C API.

Ok, get it, thanks😊 .  A little suggestion, if the cache config has an API to config it may be  more convenient, like

```cpp
WASMTIME_CONFIG_PROP(void, enable_cache, wasm_config_t*, const char* , size_t, size_t);
WASMTIME_CONFIG_PROP(void, disable_cache, wasm_config_t*);
```

https://github.com/bytecodealliance/wasmtime/blob/6e6713ae0b0be578221a2802719327526458a8cf/crates/c-api/include/wasmtime.h#L306

I use wasmtime as a library to offer wasm runtime in my library, it's not convenient for my library to create a toml file to use cache.

Again, thanks you guys for your help.

**Comment by bxq2011hust** [comment] 2021-03-24 08:38
@alexcrichton  I create a pool of instances, each instance has its own store, when a request is arrived, get an instance to process, but I failed with EXC_BAD_ACCESS. Is it possible to reuse an instance(the first use and next maybe in different thread, but each instance is used by one thread at the same time)?

**Comment by alexcrichton** [comment] 2021-03-24 14:13
Yes a strategy such as that should be safe to use from Wasmtime. You have to be sure, though, that everything connected to a store moves as a single unit between threads. If an instance is used on multiple threads over its lifetime, though, that's fine.

If you're getting faults with that strategy, though, can you gist the code you're working with so we can reproduce and investigate?

**Comment by bxq2011hust** [comment] 2021-03-24 15:40
@alexcrichton Thank you very much, it is a bug in my code. The env of function closure is invalid after execution and I forget to update the env pointer before the next execution.🤦‍♂️  Now it works well! 😄

**Comment by bxq2011hust** [comment] 2021-03-25 03:37
@alexcrichton Hi, I come back again. I meet a new problem, the instance works well before it is used under 109 times, but I try to use the instance again, I get `EXC_BAD_ACCESS`. I guess the instance has some limit(memory, stack of something), the below what I see. Do you have any ideas?
![image](https://user-images.githubusercontent.com/15418097/112415093-2ad55b80-8d5e-11eb-915f-fd5b4b1ab15f.png)
![image](https://user-images.githubusercontent.com/15418097/112415124-3d4f9500-8d5e-11eb-8f15-56453153ba32.png)
![image](https://user-images.githubusercontent.com/15418097/112415181-5a846380-8d5e-11eb-8ab1-f0575331168e.png)
![image](https://user-images.githubusercontent.com/15418097/112415206-6c660680-8d5e-11eb-9a2b-e1f94c31961c.png)

**Comment by alexcrichton** [comment] 2021-03-25 14:13
I'd recommend trying to use valgrind or perhaps thread sanitizers in C++, otherwise nothing looks too obviously awry from a quick scan. Otherwise the most useful thing I think would be to try to reduce it to a smaller program to help narrow in on what the problem is.

Instances shouldn't have limits which poison them after some use, unless they're incorrectly cleaned up, which doesn't look like it's the case there I think.

**Comment by bxq2011hust** [comment] 2021-03-26 05:54
@alexcrichton I try to use algrind trace the bug, the below is results. 
![image](https://user-images.githubusercontent.com/15418097/112500773-a289a180-8dc3-11eb-9d76-340ce4190b4a.png)

![image](https://user-images.githubusercontent.com/15418097/112500904-c1883380-8dc3-11eb-8a3a-2195176ac62f.png)

I think that the bug is in the wasm I used, there has an illegal memory access happened in the wasm, I also get `out of bounds memory access` in the trap. 

![image](https://user-images.githubusercontent.com/15418097/112572766-db5a6280-8e25-11eb-9c46-24c88ba6529a.png)

**Comment by bxq2011hust** [comment] 2021-03-26 06:08
@alexcrichton  It seems if i use linear memory in wasm and the function F in wasm exit by call host function to return a trap, the memory allocated by the F is not freed, then the next time call the F the memory usage of instance will grow. The wasm binary I used is optimized, maybe the optimized make the F not grow memory, so after many times call F the memory is out of bounds.
Is there some way to release all linear memory of an instance? Or maybe there is a better way to interrupt the execution?

**Comment by alexcrichton** [comment] 2021-03-26 16:11
Oh `valgrind` may not actually be too useful now that I think about it, wasm intentionally segfaults and raises illegal instructions, that's how we implement traps efficiently. Alas!

Currently there's no way to reset the state of an instance after each execution. For use cases like that we recommend creating new instances instead of reusing existing instances (provides better isolation for each wasm as well).

For interruption the interrupt handle is indeed intended to be invoked from anotehr thread. It can be called at any time. Interruption only affects execution, it doesn't affect linear memory. There's no way to "reset" linear memory since that's not a wasm concept per se.

**Comment by bxq2011hust** [comment] 2021-03-27 09:12
@alexcrichton  Ok, get it. Thanks again! 😄

**Closed** 2021-06-30 08:39 UTC
