### ISSUE TITLE
Failing to run a QuickJS engine ?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasmtime#4574] opened 2022-08-02 02:26 UTC
### Test Case
[qjs.txt](https://github.com/bytecodealliance/wasmtime/files/9238543/qjs.txt)
The qjs.wasm is uploaded as qjs.txt.
This report is related to https://github.com/wasmerio/wasmer/issues/1788

### Steps to Reproduce
（1）`wasmtime run qjs.wasm` or
（2）`wasmtime compile qjs.wasm` and `wasmtime run --allow-precompiled qjs.cwasm`

### Expected Results
Successfully execute the QuickJS engine and print 
"QuickJS - Type "\h" for help
qjs > "

### Actual Results
wasmtime could prints 
"QuickJS - Type "\h" for help
qjs > "
but cannot execute any qjs command in the QuickJS
when I input "console.log(new Date())" ,the wasmtime did't print the current date, however other runtime, including wasmer, WAMR could print the current date when executing the QuickJS engine.

### Versions and Environment
wasmtime 0.38.0

Operating system: macOS10.15 and ubuntu20.04

**Comment by alexcrichton** [comment] 2022-08-09 18:07
I think this is a duplicate of https://github.com/bytecodealliance/wasmtime/issues/4461, so closing.

**Closed by alexcrichton** 2022-08-09 18:07 UTC
Labels: bug

**Comment by Zhangyx24** [comment] 2022-08-10 01:38
Thanks a lot !
