### ISSUE TITLE
Possible nondeterminism bug with SIMD and new new x64 backend

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#2470] opened 2020-12-03 15:11 UTC
Recently a merged PR [failed CI on master](https://github.com/bytecodealliance/wasmtime/runs/1489518375?check_suite_focus=true) but then the next commit passed, so I'm curious if this might be an accidental bug in the new x64 backend? The errors unfortunately aren't the easiest to decipher, but wanted to open an issue to ensure we didn't lose this!

cc @abrown @jlb6740

**Comment by cfallin** [comment] 2020-12-03 17:34
Hmm, thanks for reporting -- I think the best thing to do would be to disable the failing tests for now (`simd_f32x4`, `simd_f32x4_arith`, `simd_f64x2_arith`, `simd_splat`, `simd_load` from #2432). @abrown and @jlb6740 it might be worth running under Valgrind to find uninitialized value uses; this feels like it could be such an issue. I'll create a PR to disable the tests for now.

**Comment by jlb6740** [comment] 2020-12-03 17:53
@cfallin hi yes .. this is tricky @abrown and I just talked about this. There is definitely something intermittent going on that seems to be occurring on those tests that use floating point ... so maybe affects tests that we've not seen failures in yet. I think @abrown was going to resurrect a pr to help print these values in a way that allows us to compare the expected output with the received output more cleanly but separately we were going to see if we can in a loop reproduce failures we've seen recently and running valgrind is definitely a great idea .. I will try that during investigation.

**Comment by abrown** [comment] 2020-12-04 04:38
Ok, I'm closing this in favor of https://github.com/bytecodealliance/wasmtime/issues/2432; lets make that the main tracking issue for these failures.

**Closed by abrown** 2020-12-04 04:38 UTC
