### ISSUE TITLE
can't find crate hashmap_core

### ISSUE THREAD

**Issue by frehberg** [bytecodealliance/wasmtime#26] opened 2018-11-26 12:05 UTC
with rustc 1.32.0-nightly (04fdb44f5 2018-11-03) I get the following build error.

I am updating rust now, may that will solve the issue.

```
-> /home/frehberg/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmparser-0.17.3/src/lib.rs:30:1
   |
30 | extern crate hashmap_core;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

**Comment by sunfishcode** [comment] 2018-11-26 12:14
I just fixed this issue in https://github.com/CraneStation/wasmtime/commit/f823526a42d6fb1edda623604e4c7a4e8d1f6bc0.

Unfortunately, there's still an error caused by an issue in upstream hashmap_core; https://github.com/Amanieu/hashmap_core/pull/8 fixes it.

**Comment by frehberg** [comment] 2018-11-26 12:31
sounds like I have got to wait until this has been merged into master of hashmap_core (?)

**Comment by sunfishcode** [comment] 2018-11-26 12:34
Yeah. I'll disable the fuzz check in test-all.sh for now.

**Comment by sunfishcode** [comment] 2018-11-26 13:05
Ok, I disabled it in https://github.com/CraneStation/wasmtime/commit/0e19f3983133e9a5444d3bc2fca88c1e7e98281f. test-all.sh should pass now :-).

**Comment by alexcrichton** [comment] 2020-02-01 18:00
I believe this has since been fixed, so closing.

**Closed by alexcrichton** 2020-02-01 18:00 UTC
