### ISSUE TITLE
Add support for WAT module validation/creation and API

### ISSUE THREAD

**Issue by rene-fonseca** [bytecodealliance/wasmtime#1000] opened 2020-02-26 22:06 UTC
Would it be possible to expose text format (WAT) support in the wasmtime API? Since the wasmtime exe has this feature already.

Normally binary format is just fine. However, text format is nice for EDU use-cases. E.g. when running web assembly via Jupyter.

I would like to be able to make small wat snippets that then can get run in a normal Jupyter workflow.

Example notebook at https://github.com/rene-fonseca/base/blob/master/notebooks/WebAssembly.ipynb (work in progress)

I would like to just put wat snippets in the notebook as variables and work with it.

I did try to pass on wat to the existing API which didn't get accepted. But maybe I overlooked something.

Something like:
wasm_module_new_wat()
wasm_module_validate_wat()

Maybe add a format version as second argument to make it a bit more future proff. So we can request a specific format to be used or any format version (if format gets extended at some point).

Note sure, if it makes sense but would kind of also be nice to disassemble individual functions via API. I used this feature for spidermonkey in the past to see the JavaScript source code per function.

**Comment by yurydelendik** [comment] 2020-02-26 22:14
Is it a duplicate of https://github.com/WebAssembly/wasm-c-api/issues/127 ?

**Comment by rene-fonseca** [comment] 2020-02-26 22:23
Yes, kind of.

But I would think it would take longer to get standard WASM API spec updated - instead of starting with a wasmtime API - since the functionality is there already in wasmtime :)

Should we close?

**Comment by yurydelendik** [comment] 2020-02-26 22:29
> wasm_module_new_wat()

The name looks like it belong to C API. Maybe something like `wasmtime_bytes_to_wasm`?

**Comment by rene-fonseca** [comment] 2020-02-26 22:37
Yes, that works.

Maybe use "wat" though to make it clear.
wasmtime_wat_to_wasm
wasmtime_wasm_to_wat

**Closed** 2020-03-03 16:29 UTC
Labels: enhancement, wasmtime:c-api
