### ISSUE TITLE
Error executing qjs.wasm file.

### ISSUE THREAD

**Issue by abc767234318** [bytecodealliance/wasmtime#4461] opened 2022-07-17 08:15 UTC
### Test Case

[qjs.zip](https://github.com/bytecodealliance/wasmtime/files/9127230/qjs.zip)

### Steps to Reproduce
Run the following command on Windows.
```
wasmtime .\qjs.wasm
```
Then the command line prints:
```
QuickJS - Type "\h" for help
qjs > 
```
It seems to work, but I can't type anything through the keyboard.
<br>
Run the following command on Linux.
```
wasmtime .\qjs.wasm
```
I can enter content, but there is no output from the command line.
```
QuickJS - Type "\h" for help
qjs > 1 + 1


```

**Comment by alexcrichton** [comment] 2022-07-18 13:30
This appears to be a very old build since it's still using `wasi_unstable` and not `wasi_snapshot_preview1`. Can you reproduce this with a more recent build? There have been a number of bugs fixed in the `wasi-libc` which is probably built into the wasm binary since `wasi_unstable`, so without any other information in the abstract this could very likely be a bug in the wasm itself rather than Wasmtime.

**Closed** 2022-07-20 08:35 UTC
Labels: bug
