### ISSUE TITLE
Component loading performance issue

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/wasmtime#6353] opened 2023-05-08 19:11 UTC
It takes 20 seconds to load a component in `wasmtime 7.0.0`. It is definitely much slower than loading a wasm module of comparable size. Is this expected? What could be the cause? 

wasm component file size: 6.9M

```rust
let start = Instant::now();
let component = Component::from_file(&engine, &input).unwrap();
let elapsed = start.elapsed();
println!("Time to load: {:?}", elapsed);
```

```
Time to load: 20.891809886s
```

**Comment by alexcrichton** [comment] 2023-05-08 19:25
Definitely unexpected! Do you have a component you could share to reproduce with?

**Comment by Mossaka** [comment] 2023-05-08 20:23
I do. If you clone down this [repo](https://github.com/Mossaka/wit-bindgen-go-template), and then do

```
make install-js
make build-js
```

You will get a component called `js.component.wasm`. 

You can run with `cargo run --js.component.wasm`

**Comment by alexcrichton** [comment] 2023-05-08 21:42
Sorry won't get a chance to dig into this today, but from what you pasted I think `--release` is missing? Otherwise that's building in debug mode and it's known that debug mode is much slower than release for Cranelift.

**Comment by Mossaka** [comment] 2023-05-09 18:21
Actually, I also tried to load a rust-produced wasm component with 2.0M size. The loading time is `20ms`, which is, suprisingly, significantly faster than the js component. Is this expected?

**Comment by Mossaka** [comment] 2023-05-09 18:22
```
➜  ./target/release/wit-bindgen-go-template js.component.wasm  
Time to load: 1.200816367s

➜  ./target/release/wit-bindgen-go-template rust.component.wasm 
Time to load: 20.610888ms

➜  ls rust.component.wasm 
rust.component.wasm
➜  l rust.component.wasm 
.rwxrwxr-x 2.0Mi mossaka  2 May 22:10 -I rust.component.wasm*
➜  l js.component.wasm  
.rw-rw-r-- 6.5Mi mossaka  8 May 19:06 -I js.component.wasm
```

**Comment by alexcrichton** [comment] 2023-05-09 19:51
Can you upload the `{js,rust}.component.wasm` binaries here as well? In general though yes it's probalby the case that JS is going to be longer to compile than Rust since JS has all of spidermonkey or some other JS engine

**Comment by alexcrichton** [comment] 2023-05-09 22:12
Ah right, yes, but you can `gzip` the components and upload them. (or maybe even rename it to `foo.gz` and upload it, I don't think the check is that restrictive)

**Comment by tschneidereit** [comment] 2023-05-10 11:40
I'd bet that the Rust component includes debug info, and that the code section is actually much smaller, and hence faster to compile

**Comment by Mossaka** [comment] 2023-05-19 00:38
[js.component.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/11512465/js.component.wasm.gz)
[rust.component.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/11512466/rust.component.wasm.gz)

**Comment by alexcrichton** [comment] 2023-05-19 14:22
Ok yes I can confirm that the compile times are effectively as expected. The Rust component is almost entirely debug information which can be stripped out with `wasm-tools strip`, where the JS component is almost entirely code (it is spidermonkey after all).

Given that I'm going to close this as expected where `--release` definitely should be enabled for Cranelift and the compilation pipeline, and it's expected that a JS component compiles more slowly than a Rust component.

**Closed** 2023-05-19 14:23 UTC

**Comment by SilverMira** [comment] 2025-09-06 10:29
Is it possible to specifically enable release build optimizations even without `--release` ?

I have tried `[profile.dev.package.wasmtime]` with `opt-level = 3` within Cargo.toml of my workspace but it didn't seem to help the loading times.

**Comment by bjorn3** [comment] 2025-09-06 11:15
You need to enable it for the cranelift-codegen and wasmtime-cranelift packages at the very least.
