### ISSUE TITLE
Component model: planned changes to representation of wit in binary

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/wasmtime#7023] opened 2023-09-12 22:00 UTC

**Comment by lann** [comment] 2023-09-13 16:41
@alexcrichton re: https://github.com/WebAssembly/component-model/issues/213#issuecomment-1684072335

Were you hoping for a different encoding of doc comments for preview2 or is that more of a "before 1.0" thing?

**Comment by alexcrichton** [comment] 2023-09-13 22:08
Personally I like the idea of sticking to a custom section for the near-term since it works well enough. 

Designing a format "for real" will take a nontrivial amount of energy and time. If possible I'd prefer to defer said energy and time into the future. If we one day stop reading the custom section that aligns well with, in my opinion, the intention of custom sections.

So in that sense I feel we've got all the benefit today of using a custom section minus it being "for real", and using a more official solution is hopefully postpon-able into the future.

**Comment by pchickey** [comment] 2023-09-20 22:11
https://github.com/WebAssembly/component-model/pull/248

**Comment by pchickey** [comment] 2023-10-17 18:23
@alexcrichton is going to get this complete this week, and backported into wasmtime 14 (either pre-release or as a patch)

**Comment by alexcrichton** [comment] 2023-10-19 16:24
This landed in https://github.com/bytecodealliance/wasm-tools/pull/1252 and is present in wit-component 0.16.0. Wasmtime 14 is being updated in https://github.com/bytecodealliance/wasmtime/pull/7294 and Wasmtime 15+ is updated in https://github.com/bytecodealliance/wasmtime/pull/7286

**Comment by alexcrichton** [comment] 2023-10-20 15:51
Wasmtime's test suite passes with `WIT_COMPONENT_ENCODING_V2=1` as an environment variable and I've confirmed it produces artifacts not readable with wasm-tools-1.0.47 (as expected).

I think this means everything is going smoothly, so this'll ride the same train as https://github.com/bytecodealliance/wasm-tools/issues/1205 in terms of eventually we'll switch to emitting the new syntax by default, wait another release, then purge support for the old syntax.

**Closed** 2023-11-15 17:39 UTC
Labels: wasm-proposal:component-model
