### ISSUE TITLE
--enable-threads does not enable shared memory support

### ISSUE THREAD

**Issue by RReverser** [bytecodealliance/wasmtime#1658] opened 2020-05-05 13:37 UTC
I'm using Wasmtime 0.16.0.

I've noticed that, even with, `--enable-threads`, Wasmtime fails to parse modules defining shared memories, e.g.: https://github.com/GoogleChromeLabs/wasm-feature-detect/blob/master/src/detectors/threads/module.wat

```wat
(module
  (memory 1 1 shared)
  (func
    i32.const 0
    i32.atomic.load
    drop
  )
)
```

results in:

```
Caused by:
    0: failed directive on C:\Users\rreverser\Projects\wasm-feature-detect\src\detectors\threads\module.wat:5:1
    1: WebAssembly failed to compile
    2: WebAssembly translation error
    3: Unsupported feature: shared memories
```

While I know this feature is experimental and currently not very useful in Wasmtime, it seems unexpected because the comment for `enable_threads` suggests this should work at this flag enables shared memory and atomics:

https://github.com/bytecodealliance/wasmtime/blob/c284ffe6c036b8058228d576c46688968629b48c/crates/api/src/runtime.rs#L145-L147

**Comment by bjorn3** [comment] 2020-05-05 13:47
Atomics are not implemented by Cranelift at all.

**Comment by programmerjake** [comment] 2021-03-03 22:42
> Atomics are not implemented by Cranelift at all.

they've since been implemented. https://github.com/bytecodealliance/wasmtime/issues/1059#issuecomment-679061786

**Comment by alexcrichton** [comment] 2022-05-20 18:24
I'm going to close this in favor of https://github.com/bytecodealliance/wasmtime/issues/888 since it's otherwise a duplicate of that in that we're just missing big pieces of the threads proposal right now

**Closed by alexcrichton** 2022-05-20 18:24 UTC
Labels: bug

**Comment by abrown** [comment] 2022-05-20 18:42
Just FYI: I'm working on this at the moment.
