### ISSUE TITLE
.NET: Wasmtime.TrapException: trap during instantiation

### ISSUE THREAD

**Issue by hrumhurum** [bytecodealliance/wasmtime#753] opened 2019-12-28 14:01 UTC
Trying to follow a step by step example at [https://github.com/bytecodealliance/wasmtime-demos/tree/master/dotnet](url)

It produces the following result:

```
Unhandled exception. Wasmtime.TrapException: trap during instantiation
at Wasmtime.Instance..ctor(Module module, IHost host)
at Wasmtime.Module.Instantiate(IHost host)
at WasmtimeDemo.Program.Main() in wasmtime-demos-master\dotnet\Program.cs:line 20
```

Please find enclosed `markdown.wasm` file for your further reference (not sure where the problem is located).

[markdown.zip](https://github.com/bytecodealliance/wasmtime/files/4007067/markdown.zip)

**Comment by peterhuene** [comment] 2020-01-02 20:17
Hi @hrumhurum.  Thanks for reporting this.

It looks like there's been a regression with module instantiation and I'm looking into it.

**Comment by peterhuene** [comment] 2020-01-02 20:29
It appears that the latest wasm target is putting in multiple tables:

```wat
(table (;1;) 32 anyref)
```

The instantiation succeeds if this table is omitted, but as the wasm-bindgen memory management functions are no longer being exported, the demo fails to allocate memory for the string.

**Comment by peterhuene** [comment] 2020-01-02 21:46
@hrumhurum what Rust version are you using and on what platform?  I'm having problems reproducing it on macOS, but I'm able to on Windows.

Attached should be a working `markdown.wasm` if you would like to continue with the demo while I continue my investigation.

[markdown.wasm.zip](https://github.com/bytecodealliance/wasmtime/files/4017461/markdown.wasm.zip)

**Comment by hrumhurum** [comment] 2020-01-03 11:44
rustc 1.40.0 (73528e339 2019-12-16)
Windows

**Comment by peterhuene** [comment] 2020-01-03 20:07
The underlying toolset changes appear to be breaking the other demos as well: https://github.com/bytecodealliance/wasmtime-demos/issues/13

**Comment by alexcrichton** [comment] 2020-01-06 18:42
This is likely due to the release of 0.2.56 of wasm-bindgen which includes a rewrite of how interface types are implemented. In addition to tables here wasmtime also doesn't support the new binary format for interface types, which will likely cause errors later as well. I hope to update wasmtime to the new binary representation but it's a relatively significant undertaking.

**Comment by peterhuene** [comment] 2020-01-06 21:03
That is indeed the problem.

Should we snap to `0.2.55` for markdown in `wasmtime-demos` as a workaround for now since users are going to want something working to follow along to?

**Comment by peterhuene** [comment] 2020-01-06 21:10
@hrumhurum thanks again for reporting this issue to us!

As this was caused by downstream dependencies of the demo repository, we've now merged a change that will get the markdown demo project working again.

The `master` branch of the `wasmtime-demos` repository now contains a fix.  Please pull the fix and rebuild the `markdown` project.  This should generate a wasm file that works with the .NET demo.

Please let me know if that does not resolve the issue for you.  Thanks!

**Closed by peterhuene** 2020-01-06 21:10 UTC
Labels: dotnet
