### ISSUE TITLE
wasm_name_new_from_string should not have +1 since rust strings are not null terminated.

### ISSUE THREAD

**Issue by craigsteyn** [bytecodealliance/wasmtime#2131] opened 2020-08-13 19:11 UTC
```
wasm_name_t nameWrong;
wasm_name_new_from_string(&nameWrong, "hello");
wasm_name_t nameRight;
wasm_name_new(&nameRight, strlen("hello"), "hello");
```
first one didnt work when adding to the linker.
second one did. 
Issue was caused by `wasm_name_new_from_string` adding to the length.

**Comment by alexcrichton** [comment] 2020-08-29 20:01
Sorry for the delay in getting to this, but thanks for the report! This is a discrepancy with the upstream C API in https://github.com/WebAssembly/wasm-c-api. The problem is that some string lengths include the nul terminator and some do not. Most Wasmtime APIs do not take into account the nul terminator, except for those that the wasm-c-api specifies should do so. Depending on the constructor you use you get a +1 or not as well.

It's pretty confusing, but at this time the upstream C API needs to change to make the situation better I believe.

**Comment by peterhuene** [comment] 2020-08-31 18:20
https://github.com/WebAssembly/wasm-c-api/pull/151 was made to help distinguish the fact that this function will add a null terminator to the string, which makes it unsuitable for a use such as resolving module imports.

We should update our API to match the new name.

**Closed** 2021-01-14 15:36 UTC
Labels: bug
