### ISSUE TITLE
The 22.0.0 build doesn't generate wasmtime/conf.h 

### ISSUE THREAD

**Issue by osokin** [bytecodealliance/wasmtime#8966] opened 2024-07-16 23:16 UTC
Hi,

I was using `wasmtime-c-api` cargo build target to build Wasmtime C API for previous releases.

For 22.0.0 that behavior is changed with the 566669eed20a12e8ed552abc60c51043f7702559 commit.

Could you guide me what's right approach to generate Wasmtime C API and `wasmtime/conf.h` file.

Thank you.

**Comment by clason** [comment] 2024-07-17 08:13
Duplicate of #8890 (TL;DR: use `cmake` to build wasmtime-c-api.)

**Comment by alexcrichton** [comment] 2024-07-17 14:56
Indeed this is a duplicate of https://github.com/bytecodealliance/wasmtime/issues/8890, so I'm going to close this in favor of that.

@osokin are you able to use CMake to build the C API? And/or use the release artifacts from this repository?

**Closed** 2024-07-17 14:56 UTC

**Comment by alexcrichton** [comment] 2024-07-17 22:39
If you'd like most of us in this repo are not all that familiar with CMake so if you know of ways to improve things PRs would definitely be welcome. For example running `cargo fetch` during the cmake configuration phase I think would make sense and might fix the issue you [brought up](https://github.com/bytecodealliance/wasmtime/issues/8890#issuecomment-2234134744)
