### ISSUE TITLE
Unable build: invalid bindgen output 

### ISSUE THREAD

**Issue by fckt** [bytecodealliance/wasmtime#99] opened 2019-04-09 05:19 UTC
```
cargo --version
cargo 1.33.0 (f099fe94b 2019-02-12)
rustc --version
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

`cargo build --release` gives me the following error:

```
error: unexpected close delimiter: `]`
   --> /Users/test/wasm/wasmtime/target/release/build/wasmtime-wasi-78210da8261d30eb/out/wasmtime_ssp.rs:300:39
    |
300 | # [ derive ( Copy , Clone ) ]; 2usize ] , }# [ repr ( C ) ]
    |                                       ^ unexpected close delimiter

error: aborting due to previous error
```

Looks like `rustc` can't compile a bindgen output..

**Comment by kubkon** [comment] 2019-04-09 07:46
Huh, interestingly enough I don't seem to experience this error in either debug or release build 🤔 BTW, I'm also using the latest stable release of Rust, and also building on macos.

**Comment by bnjbvr** [comment] 2019-04-09 09:47
I can't reproduce either here. This does look like a problem I've seen when building another project using bindgen. I might be asking for things you've checked before, but just in case:

- does it reproduce if you run `cargo clean`?
- any chance you have a global `bindgen` binary that is not up to date?

**Comment by fckt** [comment] 2019-04-09 22:05
It must use `bindgen` as a library I believe..
https://github.com/CraneStation/wasmtime/blob/master/wasmtime-wasi/Cargo.toml#L26

**Comment by sunfishcode** [comment] 2019-07-19 22:17
The wasmtime-wasi code mentioned here is no longer compiled in the default build of Wasmtime, which may mean this bug is fixed now. Can anyone reproduce this now?

**Comment by fckt** [comment] 2019-07-21 13:01
Yeah, works for me!

**Comment by alexcrichton** [comment] 2020-02-01 17:57
I'm going to close this since I believe the relevant code has since been removed.

**Closed by alexcrichton** 2020-02-01 17:57 UTC
