### ISSUE TITLE
Fail to append  to a file ?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasmtime#4569] opened 2022-08-01 09:04 UTC
### Test Case
[test.txt](https://github.com/bytecodealliance/wasmtime/files/9232439/test.txt)

[log.txt](https://github.com/bytecodealliance/wasmtime/files/9232458/log.txt)

The test.wasm is uploaded as test.txt.

### Steps to Reproduce
（1）`wasmtime --dir=. test.wasm '{""a"":""txt"", ""b"":1}'` or
（2）`wasmtime compile test.wasm` and `wasmtime run --allow-precompiled test.cwasm '{"a":"txt", "b":1}'`

### Expected Results
Append "txt 1" to the log.txt
And the wasm runtime wasmer could successfully append "txt 1" to the log.txt

### Actual Results
（1）Error: failed to run main module `test.wasm`

Caused by:
    0: failed to instantiate "test.wasm"
    1: command export '__rustc_debug_gdb_scripts_section__' is not a function

（2）Error: failed to run main module `test.cwasm`

Caused by:
    0: failed to instantiate "test.cwasm"
    1: command export '__rustc_debug_gdb_scripts_section__' is not a function

### Versions and Environment
wasmtime 0.38.0

Operating system: macOS

Architecture: X86_64

**Comment by sunfishcode** [comment] 2022-08-08 22:17
The issue is with the `__rustc_debug_gdb_scripts_section__` export. Wasmtime isn't running the module at all, because it doesn't recognize this export. Was this module built with `-export-all` or `-export-dynamic`? Those flags can create extra exports which shouldn't be needed for command-style modules.

**Comment by jameysharp** [comment] 2022-08-09 17:00
This is the same wasm program that was reported in #4458, so I'm closing this issue in favor of that one.

**Closed by jameysharp** 2022-08-09 17:00 UTC
Labels: bug

**Comment by Zhangyx24** [comment] 2022-08-10 01:26
Thanks a lot!
