### ISSUE TITLE
How to correctly get the right file descriptor and execute in wasmtime?

### ISSUE THREAD

**Issue by orangeC23** [bytecodealliance/wasmtime#6505] opened 2023-06-02 13:06 UTC
## Steps to reproduce
(1)'cargo new fd_advise'
(2)`cd fd_advise` and modify the main.rs :
```
fn main() {
    unsafe {
        let p1:wasi::Fd = 3; 
        let p2:wasi::Filesize = 10;
        let p3:wasi::Filesize = 20;
        let p4:wasi::Advice = wasi::ADVICE_NORMAL;
    
        println!("===[Result]===");
        println!("{:?}", wasi::fd_advise(p1, p2, p3, p4).unwrap());
    }
}
```

And add dependency in Cargo.toml:
```
[dependencies]
wasi = "0.11.0"
```
(3) `cargo build --target wasm32-wasi`
(4) execute it by wasmtime:`wasmtime run --dir=/Users/name/filetest ./target/wasm32-wasi/debug/fd_advise.wasm` and it prints
![image](https://github.com/bytecodealliance/wasmtime/assets/28601300/9b6a973c-5b92-42a0-8b5a-6d813eee83cd)

(5) execute it by wasmer:`wasmer --dir=/Users/name/filetest ./target/wasm32-wasi/debug/fd_advise.wasm ` and it prints:
![image](https://github.com/bytecodealliance/wasmtime/assets/28601300/41662979-5bff-460b-9bbe-6c1c37e4e3e0)

 without panic

Maybe I use wasmtime with wrong code ?

**Comment by pchickey** [comment] 2023-06-02 18:08
@bjorn3 is correct: wasmtime's wasi implementation fails BADF on directories because fd_advise does not work on directories. In your example, fd `3` is a preopened directory.

**Comment by pchickey** [comment] 2023-06-02 18:26
Since I believe what you described is the intended behavior, I'm going to close this issue, but please re-open if my understanding of the problem is incorrect.

**Closed by pchickey** 2023-06-02 18:26 UTC

**Comment by bjorn3** [comment] 2023-06-02 18:27
Would it make sense to add a test that the wasi implementation will return EBADF for fd_advise on directories?

**Comment by orangeC23** [comment] 2023-06-04 02:02
Thanks a lot !

**Comment by yamt** [comment] 2023-12-07 05:45
it sounds like a bug (or a restriction) in wasmtime to me.

in posix environments, it's common to ignore fadvice on directory.
wasi doesn't seem to have a word about the case. (so i expect it to follow posix equivalent.)

besides that, if you want to make it fail for some reasons, i feel it's more natural to use EISDIR than EBADF.
