### ISSUE TITLE
Storing Memory Exported By Wasm Module In State

### ISSUE THREAD

**Issue by AldaronLau** [bytecodealliance/wasmtime#4922] opened 2022-09-18 03:06 UTC
#### Feature

Ability to import memory before sending state to wasmtime API.

#### Benefit

Prevent having to use an `Option` or `MaybeUninit` in the state to store `Memory` in state when it's always going to be `Some` or initialized by the time a function call from WASM happens.

#### Implementation

Most likely would require postponing when the state is shared with wasmtime (so the memory can be imported from the wasm module and stored into a state).  This could occur after instantiating, possibly with another type.

#### Alternatives

 - Keep using `Option` or `MaybeUninit`

 - Possibly change `Func::call` so that it needs to manually pass in the user state as an additional parameter

**Comment by bjorn3** [comment] 2022-09-18 07:12
Instantiating needs the state as it calls the start function of the wasm module, which can call back to the host functions that use the state AFAIK.

**Comment by AldaronLau** [comment] 2022-09-20 03:31
Thanks, that makes sense.

Would it be possible to add an API to wasmtime similar to [`wasmi::InstancePre::ensure_no_start()`](https://docs.rs/wasmi/latest/wasmi/struct.InstancePre.html#method.ensure_no_start), which additionally would not require the user provided state until after instantiation?

Or considering this from the WASM spec:

> The component of a module declares the [function index](https://www.w3.org/TR/wasm-core-2/syntax/modules.html#syntax-funcidx) of a start function that is automatically invoked when the module is [instantiated](https://www.w3.org/TR/wasm-core-2/exec/modules.html#exec-instantiation), after [tables](https://www.w3.org/TR/wasm-core-2/syntax/modules.html#syntax-table) and [memories](https://www.w3.org/TR/wasm-core-2/syntax/modules.html#syntax-mem) have been initialized.

Since memories and tables are initialized *before* the start function is called, would it be possible to split into a two-stage initialization?  I'm assuming memories and tables wouldn't require the user's state, and that the state would only be required right before the invocation of the start function.

**Comment by alexcrichton** [comment] 2022-09-21 14:23
While that could be theoretically done I don't think I understand fully why we would do that. Is having an `Option` onerous to represent the pre-instantiated and post-instantiated state?

**Comment by AldaronLau** [comment] 2022-09-21 14:59
My specific use case can be very I/O bound, so if the `Option` can be removed that's possibly around 1000+ branches in unwraps / second (for calls back to the host, all of which need to read/write the memory exported by the wasm module).  It would help for both battery life and efficiency, if it can be safely proved at compile time that it would be initialized.

**Comment by bjorn3** [comment] 2022-09-21 15:07
The branch will likely be correctly predicted in the fast majority of the cases, which means that the overhead is very small. The overhead to call from wasm into host code is much bigger.

**Comment by AldaronLau** [comment] 2022-09-21 15:14
Maybe it's not as big of a deal as I was initially thinking.  I would just prefer to move checks from runtime to compile time if possible.

**Comment by alexcrichton** [comment] 2022-12-02 00:01
I'm going to close this as I think it was answered above.

**Closed by alexcrichton** 2022-12-02 00:01 UTC

**Comment by Lohann** [comment] 2024-11-07 08:00
Hello, can we reopen this issue? I had a lot of trouble and work to get Wasmtime store working with [MaybeUnit](https://doc.rust-lang.org/beta/std/mem/union.MaybeUninit.html), this simple solution segfaults:

```rust
pub struct State {
    pub memory: Memory,
}

let state = MaybeUninit::<State>::uninit();
let mut store = Store::new(engine, state);

let memory_type = MemoryType::new(16, None);
store.data_mut().memory.write(Memory::new(&mut store, memory_type)?);

let store = unsafe {
    std::mem::transmute::<Store<MaybeUninit<State>>, Store<State>>(store)
};

// segfaults below
let instance = Instance::new(&mut store, &module, &imports)?;
```

Then I realized the issue is that there's no way for me transmute only the `State`, I need to transmute the `Store` which is not recommended, once rust [doesn't guarantee the same memory layout](https://doc.rust-lang.org/beta/std/mem/union.MaybeUninit.html#layout-1):
```rust
assert_eq!(size_of::<Option<bool>>(), 1);
assert_eq!(size_of::<Option<MaybeUninit<bool>>>(), 2);
```

Actually I haven't find any way to use MaybeUnit that doesn't look hacky, and I want to avoid the usage of `Option` and `unwraps` in the code, once it bloats the binary with panic data.

**Comment by alexcrichton** [comment] 2024-11-07 15:46
It's best to open a new issue for questions like this, as I see you've done on https://github.com/bytecodealliance/wasmtime/issues/9579, so I'll answer over there.
