### ISSUE TITLE
wasmtime does not allow network functionality throws operation not implemented error

### ISSUE THREAD

**Issue by kmehant** [bytecodealliance/wasmtime#5867] opened 2023-02-23 16:44 UTC
### Description

```sh
wasmtime run --tcplisten localhost:8080 --wasm-features=all  wasm_with_network_code.wasm localhost 8080
```
output:

```
operation not implemented
```

```sh
wasmtime run --wasm-features=all  wasm_with_network_code.wasm localhost 8080
```
output:

```
operation not implemented
```

### Steps to reproduce

Build Go program with the below code with wasi target
```go
// os.Args[1] -> localhost
// os.Args[2] -> 8080
server, err := net.Listen("tcp", os.Args[1]+":"+os.Args[2])
```

run the wasm module with wasmtime

```sh
wasmtime run --wasm-features=all  wasm_with_network_code.wasm localhost 8080
```

or 

```sh
wasmtime run --tcplisten localhost:8080 --wasm-features=all  wasm_with_network_code.wasm localhost 8080
```

### Expected behavior
start a server and listen at localhost:8080 and accept requests

### Actual behavior
fails with message operation not implemented

### Versions and Environment

Wasmtime version or commit: wasmtime-cli 5.0.0

Operating system: Mac OS Monterey

Architecture: AMD 64

**Comment by pchickey** [comment] 2023-02-23 17:59
Can you provide a wasm binary we can use to reproduce?

**Comment by kmehant** [comment] 2023-02-23 18:05
[server.wasm.zip](https://github.com/bytecodealliance/wasmtime/files/10816809/server.wasm.zip)

@pchickey Here it is. Thanks

**Comment by bjorn3** [comment] 2023-02-23 18:11
How was the binary compiled? From what I can gather go doesn't yet support wasi. Are you using tinygo? I think tinygo doesn't support network functionality yet and throws that exact "operation not implemented" error: https://github.com/tinygo-org/tinygo/blob/0d56dee00f49bd50eb373c02c30062a75ec28f10/src/net/dial.go#L20

**Comment by kmehant** [comment] 2023-02-23 18:12
> How was the binary compiled? From what I can gather go doesn't yet support wasi. Are you using tinygo? I think tinygo doesn't support network functionality yet and throws that exact "operation not implemented" error: https://github.com/tinygo-org/tinygo/blob/0d56dee00f49bd50eb373c02c30062a75ec28f10/src/net/dial.go#L20


@bjorn3 Ah, got it, thanks. 

Are there any alternatives?

**Comment by bjorn3** [comment] 2023-02-23 18:15
You could ask tinygo to add support for it. Alternatively you could try directly binding to wasi's sock_accept, but I'm not sure if tinygo allows that or puts it's own standard library in a privileged position.

**Comment by pchickey** [comment] 2023-02-23 18:36
I'll close this because it appears to be a tinygo issue

**Closed by pchickey** 2023-02-23 18:36 UTC
Labels: bug
